kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:stable-otel
    # ports: # Without also by default runs on port 80
    # - containerPort:80

#  We didn't given any namespace --> running in default namespace