kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources: # Soft limit
      requests:
        cpu: "100m"
        memory: "128Mi" 
      limits: # Limits can be >= requests but NOT <
        cpu: "100m"
        memory: "128Mi"

