apiVersion: v1
kind: ConfigMap
metadata:
  name: daws78s # This is name of ConfigMap
data:
  course: "DevOps with AWS"
  trainer: "Manikanta Reddy"
  github: "https://github.com/daws-78s/k8-resources"