apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - confifMapRef:
        name: daws78s # This fetches all values inside ConfigMap

    # OR (Below is lot of code)

    # env:
    # - name: course # Taking value from ConfigMap (08-...)
    #   valueFrom:
    #     configMapKeyRef:
    #       name: daws78s
    #       key: course
    # - name: trainer
    #   valueFrom:
    #     configMapKeyRef:
    #       name: daws78s
    #       key: trainer
