apiVersion: v1
kind: Secret
metadata:
  name: pod-secret
data:
  username: "YWRtaW4K" # in Git --> echo "admin" | base64
  password: "YWRtaW4xMjMK" # echo "admin123" | base64

  # Instead of keeping directly we keep encoded