kind: Pod
apiVersion: v1
metadata:
  name: nginx
  labels:
    name: service-test
    project: expense
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx