kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec: 
  selector:
    name: service-test
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 # Service - Port
    targetport: 80 # Target - Port