kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  # These labels are deployment related labels
  labels:
    app: nginx
    purpose: deployment
    tier: web
spec: # Not part of metadata
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: test-project
  # POD Definition
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        project: test-project
        extra-key: extra-value
    spec: # Part of metadata
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    tier: web
    project: test-project
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port